# Generated by Django 5.2.1 on 2025-05-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Genre', models.CharField(max_length=20)),
                ('Cost', models.IntegerField()),
                ('Run', models.FloatField()),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
